# Generated by Django 5.0.3 on 2024-03-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_day_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
